### ISSUE TITLE
Error while using JNAMemorySnapshotter

### ISSUE THREAD

**Issue by x7airworker** [Jire/grapple#2]
```Java
package me.x7airworker.csgocheat;

import com.sun.jna.platform.win32.WinNT;
import org.jire.grapple.Process;
import org.jire.grapple.ProcessFinder;
import org.jire.grapple.snapshotter.JNAMemorySnapshotter;

import java.util.List;

public class CSGOCheat
{
    private static Process process;

    public static void main(String[] args)
    {
        process = getProcess();

        new JNAMemorySnapshotter(process) {
            @Override
            public void afterSnapshot()
            {
                System.out.println("hi");
            }
        }.takeSnapshot();
    }

    private static Process getProcess()
    {
        List<Process> processes = ProcessFinder.findProcessesByName("csgo.exe",
WinNT.PROCESS_QUERY_INFORMATION | WinNT.PROCESS_VM_READ | WinNT.PROCESS_VM_WRITE);
        while(processes.size() < 1)
        {
            System.out.println("CS:GO wasn't found...");
            try
            {
                Thread.sleep(1000 * 10);
            }
            catch (InterruptedException e)
            {
                e.printStackTrace();
            }
            processes = ProcessFinder.findProcessesByName("csgo.exe", WinNT.PROCESS_QUERY_INFORMATION | WinNT.PROCESS_VM_READ | WinNT.PROCESS_VM_WRITE);
        }

        System.out.println("CS:GO was found...");

        return processes.get(0);
    }
}
```
Stacktrace:
CS:GO was found...
Exception in thread "main" java.lang.IllegalArgumentException: Allocation size must be greater than zero
	at com.sun.jna.Memory.<init>(Memory.java:111)
	at org.jire.grapple.snapshotter.JNAMemorySnapshotter.<init>(JNAMemorySnapshotter.java:31)
	at me.x7airworker.csgocheat.CSGOCheat$1.<init>(CSGOCheat.java:18)
	at me.x7airworker.csgocheat.CSGOCheat.main(CSGOCheat.java:18)

Process finished with exit code 1

**Comment by Jire** [comment]
The snapshotter doesn't support Process yet

**Comment by jonatino** [comment]
👶 🍼
